In [ ]:
import numpy as np
from scipy import stats

salary = [102, 33, 26, 27, 30, 25, 33, 33, 24]

mean_salary = np.mean(salary)
print("mean:", mean_salary)

median_salary = np.median(salary)
print("median:", median_salary)

mode_salary = stats.mode(salary)
print("mode:", mode_salary)

mode_salary = stats.mode(salary, keepdims=False)
print("mode:", mode_salary)

mode_salary = stats.mode(salary, keepdims=True)
print("mode:", mode_salary)

In [ ]:
#NumPy
#Pandas
#SciPy (stats)
#Seaborn  (gorsellestirme)
#Matplotlib (gorsellestirme)

In [2]:
print(np.__version__)

1.21.5


In [21]:
import numpy as np
import seaborn as sns
from scipy import stats

In [15]:
import scipy

In [16]:
a = [5,7,10,15,19,21,21,22,22,23,23,23,23,23,24,24,24,24,25]

In [19]:
scipy.stats.mode(a)

/var/folders/rj/btv0gg5s6k311rng_vg2r35w0000gn/T/ipykernel_71347/3408956811.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  scipy.stats.mode(a)


ModeResult(mode=array([23]), count=array([5]))

In [5]:
len(a)

19

In [6]:
print(np.mean(a))

print(np.median(a))

print(stats.mode(a))

19.894736842105264
23.0
ModeResult(mode=array([23]), count=array([5]))


/var/folders/rj/btv0gg5s6k311rng_vg2r35w0000gn/T/ipykernel_47645/2992882565.py:5: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print(stats.mode(a))


In [11]:
stats.mode(a)[0]

/var/folders/rj/btv0gg5s6k311rng_vg2r35w0000gn/T/ipykernel_47645/3728512739.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(a)[0]


array([23])

In [10]:
stats.mode(a)[0][0]

/var/folders/rj/btv0gg5s6k311rng_vg2r35w0000gn/T/ipykernel_47645/1558523222.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(a)[0][0]


23

In [8]:
stats.mode(a)[1]

/var/folders/rj/btv0gg5s6k311rng_vg2r35w0000gn/T/ipykernel_47645/2732935528.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(a)[1]


array([5])

In [13]:
np.min(a)

5

In [14]:
np.max(a)

25

In [23]:
q1 = np.percentile(a, 25)

q1

20.0

In [24]:
q3 = np.percentile(a, 75)

q3

23.5

In [20]:
q2 = np.percentile(a, 50)

In [25]:
IQR = q3 - q1

IQR

3.5

In [26]:
stats.iqr(a)

3.5

In [27]:
np.percentile(a, [25, 50, 75])

array([20. , 23. , 23.5])

In [4]:
a = [8, 10, 4, 24, 8, 3, 10, 3, 40, 7, 6, 12, 4]

np.percentile(a, [75]) - np.percentile(a, [25])

array([6.])

In [18]:
help(np.percentile)  # help() fonksiyonu orneklerle bir fonsiyonu aciklar

Help on function percentile in module numpy:

percentile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)
    Compute the q-th percentile of the data along the specified axis.
    
    Returns the q-th percentile(s) of the array elements.
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    q : array_like of float
        Percentile or sequence of percentiles to compute, which must be between
        0 and 100 inclusive.
    axis : {int, tuple of int, None}, optional
        Axis or axes along which the percentiles are computed. The
        default is to compute the percentile(s) along a flattened
        version of the array.
    
        .. versionchanged:: 1.9.0
            A tuple of axes is supported
    out : ndarray, optional
        Alternative output array in which to place the result. It must
        have the same shape and buffer length as the expected output,
     

# Variance and Standard Deviation

In [28]:
np.var(a)

34.93628808864266

In [29]:
np.std(a)  # population std

5.910692691101667

In [33]:
np.std(a, ddof=1)  # sample std (n-1)'e boler

6.0726594653789165

In [30]:
np.sqrt(np.var(a))

5.910692691101667

In [1]:
b = [0,0,0,2,4,4,4]

In [3]:
np.std(b)  # population std

1.8516401995451028

In [4]:
np.var(b)

3.4285714285714284

In [5]:
c = [0,2,2,2,2,2,4]

In [6]:
np.std(c)  # population std

1.0690449676496976

In [7]:
np.var(c)

1.1428571428571428

# Skewness

In [31]:
stats.skew(a)  # a is negatively skewed

-1.5176315809887007

In [32]:
stats.describe(a)

DescribeResult(nobs=19, minmax=(5, 25), mean=19.894736842105264, variance=36.877192982456144, skewness=-1.5176315809887007, kurtosis=0.8528442245963328)

In [20]:
stats.kurtosis(a)

0.8528442245963328

In [14]:
samples = np.random.normal(loc=100, scale=15, size=1000)
samples

array([101.98443207,  77.91185708, 105.2908661 ,  84.99941326,
       102.05253158,  91.2029072 ,  88.39000367,  81.88864821,
       122.04233496, 117.46992685,  77.71916414, 107.4214242 ,
        84.6257924 , 106.58224331,  96.85795882,  93.34332262,
        84.13022087,  78.88118077, 107.07109558, 124.59251989,
       128.21205754, 104.21362258,  65.93082161, 111.26788668,
        99.52838471, 110.14875883, 108.36052554,  82.89270263,
        98.18471557,  68.55891062, 103.09674438,  89.82255034,
       109.45995333, 120.345171  , 107.57899753, 105.52066864,
       104.51980631,  85.32889691, 125.07159393, 114.06567802,
        72.65030638,  98.42677527,  81.54712094,  69.03903915,
        86.38535775, 110.01222969,  94.90069295, 102.68883637,
        99.19701731, 108.20081094, 103.78061306, 102.61007204,
        80.17297429, 107.81335788, 107.7614375 , 104.4752604 ,
       122.94462547, 108.61993307,  95.76513838,  69.51792416,
        82.04983942,  70.80384607,  76.32881249, 112.04

In [40]:
a = [1, 4, 7, 9, 10]
b = [4, 9, 10, 15]
c = [2, 4, 5, 7, 8, 9, 11]
d = [1,2,3,5,6,9,9,10,11,12]

In [41]:
print(np.percentile(a, 25))
print(np.percentile(b, 25))
print(np.percentile(c, 25))
print(np.percentile(d, 25))

4.0
7.75
4.5
3.5
